(function (global) {
  'use strict';
  var PLACES=['wall','ceiling','floor','partition'];
  var LABEL={ru:{wall:'Стена',ceiling:'Потолок',floor:'Пол',partition:'Перегородка',title:'Сколько это стоит',lead:'Введите площадь. Если тариф для выбранной конструкции уже задан — увидите диапазон; если нет, отправьте площадь на точный расчёт.',place:'Что звукоизолируем',area:'Площадь, м²',result:'Ориентировочная стоимость',noPrice:'Цена зависит от выбранной системы — рассчитаем по вашему объекту.',cta:'Получить расчёт'},kz:{wall:'Қабырға',ceiling:'Төбе',floor:'Еден',partition:'Қалқа',title:'Құны қанша',lead:'Ауданды енгізіңіз. Тариф енгізілген болса — диапазон көрсетіледі; болмаса нақты есепке жіберіңіз.',place:'Нені оқшаулаймыз',area:'Аудан, м²',result:'Болжамды құн',noPrice:'Баға жүйеге байланысты — нысаныңызға есептейміз.',cta:'Есеп алу'},en:{wall:'Wall',ceiling:'Ceiling',floor:'Floor',partition:'Partition',title:'How much does it cost',lead:'Enter the area. If a rate is configured you will see a range; otherwise send the area for an exact quote.',place:'What to soundproof',area:'Area, m²',result:'Estimated price',noPrice:'Price depends on the selected system — we will calculate it for your property.',cta:'Get a quote'}};
  function render(node){var C=global.SILENCE_CORE,cfg=global.PRICING||{},lang=C.getLang(),x=LABEL[lang]||LABEL.ru;node.hidden=false;node.innerHTML='';var wrap=C.el('div',{class:'container'});wrap.appendChild(C.el('div',{class:'section-heading'},[C.el('h2',{},[x.title]),C.el('p',{class:'lead'},[x.lead])]));
    var box=C.el('div',{class:'price-calc'});var sf=C.el('div',{class:'field'},[C.el('label',{for:'price-place'},[x.place])]);var sel=C.el('select',{id:'price-place'},PLACES.map(function(p){return C.el('option',{value:p},[x[p]]);}));sf.appendChild(sel);var af=C.el('div',{class:'field'},[C.el('label',{for:'price-area'},[x.area]),C.el('input',{id:'price-area',type:'number',min:'1',step:'1',value:'12'})]);var inp=af.querySelector('input');var result=C.el('div',{class:'price-calc__result'},[C.el('span',{class:'caption u-muted'},[x.result]),C.el('strong',{class:'price-calc__value'})]);var value=result.querySelector('.price-calc__value');var quote=C.el('a',{class:'btn btn--primary price-calc__cta','data-analytics':'price_quote_click'},[x.cta]);
    function recalc(){var r=global.SILENCE_CALC_PRICE&&global.SILENCE_CALC_PRICE(sel.value,inp.value);value.textContent=r?(r.lo.toLocaleString('ru-RU')+'–'+r.hi.toLocaleString('ru-RU')+' '+r.currency):x.noPrice;var q=new URLSearchParams({surface:sel.value,area:inp.value||''});quote.href='contacts.html?'+q.toString();}
    sel.addEventListener('change',recalc);inp.addEventListener('input',recalc);box.appendChild(sf);box.appendChild(af);box.appendChild(result);box.appendChild(quote);wrap.appendChild(box);node.appendChild(wrap);recalc();}
  global.SILENCE_PAGES=global.SILENCE_PAGES||{};global.SILENCE_PAGES.pricing=render;
}(window));
