/* v27: one hit map for mouse, touch and keyboard. Image proportions never change. */
(function(g){
 'use strict';
 var zones=[{id:'top',n:'1',x:0,y:0,w:100,h:30},{id:'left',n:'2',x:0,y:30,w:29,h:38},{id:'right',n:'3',x:71,y:30,w:29,h:38},{id:'bottom',n:'4',x:0,y:68,w:100,h:32}];
 function render(node){
  var C=g.SILENCE_CORE,D=g.SILENCE_V27,U=g.SILENCE_V27_UI,lang=C.getLang();function t(k){return U.t(k);}function tr(r,k,e){return lang==='kz'?k:lang==='en'?e:r;}
  var overlay=node.querySelector('[data-cutaway-overlay]'),host=node.querySelector('[data-cutaway-content]'),choices=node.querySelector('[data-room-choices]');if(!overlay||!host||!choices)return;
  overlay.innerHTML='';host.innerHTML='';choices.innerHTML='';
  var entries=[
   {id:'top',short:tr('Сверху','Жоғарыдан','Above'),title:tr('Сверлят и стучат сверху','Жоғарыдан бұрғылау мен соққы','Drilling and impacts above'),desc:tr('Для потолка рассматриваем систему с виброразвязкой. При ударах и ремонте сначала проверяем, как звук передаётся через перекрытие и примыкания.','Төбе үшін дірілді ажырататын жүйе қарастырылады. Алдымен дыбыстың жабын мен түйіспелер арқылы таралуын тексереміз.','Consider an isolated ceiling assembly. First assess how impacts and drilling travel through the slab and adjoining junctions.'),place:'ceiling',systems:['c-apex','c-comfort','c-premium']},
   {id:'left',short:tr('Слева','Сол жақтан','Left'),title:tr('Разговоры и бытовой шум за стеной','Қабырға артындағы әңгіме мен тұрмыстық шу','Speech and household noise behind the wall'),desc:tr('Дополнительная облицовка существующей стены. Конструкцию выбирают с учётом основания, розеток, щелей и примыканий.','Бар қабырғаның қосымша қаптамасы. Негіз, розеткалар, саңылаулар мен түйіспелер ескеріледі.','Additional lining for an existing wall. Selection depends on the base, sockets, gaps and junctions.'),place:'wall',systems:['wf-standart','w-comfort','w-premium']},
   {id:'right',short:tr('Справа','Оң жақтан','Right'),title:tr('Музыка через стену справа','Оң жақ қабырға арқылы музыка','Music through the right wall'),desc:tr('Для музыки и баса особенно важны исходная стена и обходные пути передачи. Ниже — варианты стеновых конструкций для обсуждения со специалистом.','Музыка мен бас үшін қабырға мен жанама берілу жолдары маңызды. Төменде маманмен талқылауға арналған қабырға жүйелері.','For music and bass, the existing wall and flanking paths matter. These wall assemblies are starting points for a specialist assessment.'),place:'wall',systems:['w-comfort','w-premium','w-business']},
   {id:'bottom',short:tr('Снизу','Төменнен','Below'),title:tr('Басы и разговоры снизу','Төменнен бас пен әңгіме','Bass and speech from below'),desc:tr('Звук может идти через перекрытие, стены и примыкания. Напольную систему против вашего топота нельзя автоматически назначать для шума, приходящего снизу.','Дыбыс жабын, қабырға және түйіспелер арқылы келуі мүмкін. Өз қадамыңызға арналған еден жүйесін төменнен келетін шуға автоматты түрде ұсынуға болмайды.','Sound may travel through the floor slab, walls and junctions. A floor system for your own footsteps is not automatically a solution for incoming noise from below.'),diagnostic:true},
   {id:'impact-down',short:tr('Мой топот слышат снизу','Қадамымды төменнен естиді','My footsteps disturb downstairs'),title:tr('Системы звукоизоляции пола','Еденді дыбыстан оқшаулау жүйелері','Floor sound-insulating assemblies'),desc:tr('Задача — снизить передачу ударного шума от вашего пола вниз. Выбор зависит от основания, покрытия и допустимой высоты конструкции.','Мақсат — еденнен төменге берілетін соққы шуды азайту. Таңдау негізге, жабынға және рұқсат етілген биіктікке байланысты.','Reduce impact-noise transmission from your floor downwards. Selection depends on the base, finish and available build-up height.'),place:'floor',systems:['f-antistomp','f-sfgb','f-sf']},
   {id:'echo',short:tr('Эхо в комнате','Бөлмедегі жаңғырық','Echo in the room'),title:tr('Акустика внутри помещения','Бөлме ішіндегі акустика','Room acoustics'),desc:tr('Для работы с отражениями и эхом нужны интерьерные звукопоглощающие панели. Это отдельная задача, не замена звукоизоляции от соседей.','Шағылу мен жаңғырық үшін интерьерлік дыбыс жұтқыш панельдер қажет. Бұл көршілерден дыбыс оқшаулауды алмастырмайтын бөлек міндет.','Interior sound-absorbing panels address reflections and reverberation. This is a separate task, not a substitute for insulation from neighbours.'),echo:true}
  ];
  var buttons=[],hits=[];
  function select(id,user){var e=entries.find(function(x){return x.id===id;});if(!e)return;node._selectedProblem=id;node.dataset.activeRoom=id;g.SILENCE_CONSULTATION_CONTEXT={problem:id,label:e.title};document.dispatchEvent(new CustomEvent('silence:problem',{detail:g.SILENCE_CONSULTATION_CONTEXT}));
   buttons.concat(hits).forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.room===id));});host.innerHTML='';host.className='room27-result';
   var q='contacts.html?problem='+encodeURIComponent(id)+(e.place?'&surface='+e.place:'');var copy=C.el('div',{class:'room27-result__copy'},[C.el('p',{class:'eyebrow'},[t('selection')]),C.el('h2',{},[e.title]),C.el('p',{},[e.desc]),C.el('a',{class:'btn btn--primary',href:q,'data-analytics':'consultation_scenario','data-analytics-value':id},[t('cta')])]);host.appendChild(copy);
   var rec=C.el('div',{class:'room27-recommendations'});
   if(e.systems){rec.appendChild(C.el('p',{class:'eyebrow'},[t('options')]));e.systems.forEach(function(sid){var s=g.CATALOG.systems.find(function(x){return x.id===sid;});if(!s)return;var b=C.el('button',{type:'button',class:'room27-system','data-system':s.id},[C.el('span',{},[s.name]),C.el('span',{class:'room27-system__rating'},[s.ix+' '+s.from+(s.to!==s.from?'–'+s.to:'')+' '+tr('дБ','дБ','dB'),C.el('span',{'aria-hidden':'true'},[' ↗'])])]);b.addEventListener('click',function(){C.openCardOverlay(C.renderCardBody(s,lang));});rec.appendChild(b);});rec.appendChild(C.el('p',{class:'source27-note'},[t('notGuarantee')]));}
   else if(e.echo){['acousticwood','reverboard','acousticloft'].forEach(function(parent){var p=D.products.find(function(x){return x.parent===parent;});var b=C.el('button',{type:'button',class:'room27-system'},[C.el('span',{},[parent==='acousticwood'?'AcousticWood':parent==='reverboard'?'ReverBoard':'AcousticLoft']),C.el('span',{'aria-hidden':'true'},['↗'])]);b.addEventListener('click',function(){U.openProduct(p);});rec.appendChild(b);});}
   else {rec.appendChild(C.el('div',{class:'diagnostic27'},[C.el('span',{class:'diagnostic27-symbol','aria-hidden':'true'},['↗']),C.el('h3',{},[tr('Сначала — диагностика','Алдымен — диагностика','Assessment first')]),C.el('p',{},[tr('Опишите шум и конструкцию помещения. По одному направлению звука нельзя выбрать готовую систему.','Шуды және бөлме конструкциясын сипаттаңыз. Бір бағыт бойынша дайын жүйені таңдау мүмкін емес.','Describe the noise and construction. The direction alone is not enough to prescribe an assembly.')])]));}
   host.appendChild(rec);if(user&&g.SILENCE_TRACK)g.SILENCE_TRACK('room_selection',{value:id});
  }
  zones.forEach(function(z){var e=entries.find(function(x){return x.id===z.id;});var b=C.el('button',{type:'button',class:'room27-hotspot room27-hotspot--'+z.id,'data-room':z.id,'aria-label':e.title,'aria-pressed':'false','aria-controls':'room27-result'},[C.el('span',{class:'room27-pin','aria-hidden':'true'},[z.n])]);b.style.left=z.x+'%';b.style.top=z.y+'%';b.style.width=z.w+'%';b.style.height=z.h+'%';b.addEventListener('click',function(){select(z.id,true);});overlay.appendChild(b);hits.push(b);});
  entries.forEach(function(e,i){var b=C.el('button',{type:'button',class:'room27-choice','data-room':e.id,'aria-pressed':'false','aria-controls':'room27-result'},[i<4?C.el('span',{class:'room27-choice__num','aria-hidden':'true'},[String(i+1)]):null,e.short]);b.addEventListener('click',function(){select(e.id,true);});choices.appendChild(b);buttons.push(b);});
  if(node._selectedProblem)select(node._selectedProblem,false);else{host.className='room27-result room27-result--empty';host.appendChild(C.el('div',{},[C.el('p',{class:'eyebrow'},[t('selection')]),C.el('h2',{},[t('resultTitle')]),C.el('p',{},[t('resultIntro')])]));}
 }
 g.SILENCE_PAGES=g.SILENCE_PAGES||{};g.SILENCE_PAGES['section-cutaway']=render;g.SILENCE_SECTION={ZONES:zones};
}(window));
